http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h
users:
  - name: dff652
    password: $2a$10$85yVejdu0VRUtQQpZH4iJ.nxP2Fxc/MeyZUyjk66vV426YEY0b//G
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 0
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 127.0.0.1:7874
    - '[/lan/]127.0.0.1:5335'
    - '[/localhost/]127.0.0.1:5335'
  upstream_dns_file: ""
  bootstrap_dns:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
    - 1.1.1.1
  fallback_dns: []
  upstream_mode: parallel
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 83886080
  cache_ttl_min: 60
  cache_ttl_max: 600
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: true
  edns_client_subnet:
    custom_ip: ""
    enabled: true
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
    - 127.0.0.1:5335
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  dir_path: ""
  ignored:
    - o1098464.ingest.sentry.io
  interval: 168h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  dir_path: ""
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://anti-ad.net/easylist.txt
    name: easylist
    id: 1680273454
  - enabled: false
    url: https://easylist-downloads.adblockplus.org/easyprivacy.txt
    name: easyprivacy隐私
    id: 1680273457
  - enabled: false
    url: https://easylist-downloads.adblockplus.org/easylistchina.txt
    name: easylistchina
    id: 1680273458
  - enabled: false
    url: https://banbendalao.coding.net/p/adgk/d/ADgk/git/raw/master/ADgk.txt
    name: adgk手机去广告规则
    id: 1680273459
  - enabled: true
    url: https://gist.githubusercontent.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf/raw/b9318009399b99e822515d388b8458557d828c37/hosts-yt-ads
    name: YouTube-去广告
    id: 1680273460
  - enabled: false
    url: https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts
    name: Google hosts – 提高网站访问速度
    id: 1680285869
  - enabled: false
    url: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
    name: 1024_hosts – 1024网站和澳门皇家赌场
    id: 1680285871
  - enabled: false
    url: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
    name: 大圣净化 – 针对国内视频网站
    id: 1680285872
  - enabled: false
    url: https://winhelp2002.mvps.org/hosts.txt
    name: Mvps – 屏蔽美欧地区英文网站相关的广告
    id: 1680285873
  - enabled: false
    url: https://raw.githubusercontent.com/vokins/yhosts/master/hosts
    name: yhosts – 屏蔽国内网站广告-国内维护
    id: 1680285874
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad-pc.txt
    name: ad-pc
    id: 1680363252
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt
    name: ad-mo.txt
    id: 1680363253
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/anti-ad-easylist.txt
    name: anti-AD
    id: 1686886176
  - enabled: true
    url: https://ghp.ci/raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/dns.txt
    name: GOODBYEADS
    id: 1728295210
  - enabled: true
    url: https://mirror.ghproxy.com/raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/adblock.txt
    name: GOODBYEADS1
    id: 1728295211
whitelist_filters: []
user_rules:
  - '||active.tc.skysrt.com^'
  - '||ad.3.cn^'
  - '||admaster.com.cn^'
  - '||alog.umeng.com^'
  - '||amdcopen.m.taobao.com^'
  - '||api.app.skysrt.com^'
  - '||api.device.skysrt.com^'
  - '||api.hoisin.hw.coocaatv.com^'
  - '||api.home.skysrt.com^'
  - '||api.skyworthiot.com^'
  - '||api.upgrade.skysrt.com^'
  - '||api-app.coocaa.ottcn.com^'
  - '||api-home.coocaa.ottcn.com^'
  - '||api-home.skysrt.com^'
  - '||api-upgrade.coocaa.ottcn.com^'
  - '||app.snm0516.aisee.tv^'
  - '||btrace.play.t002.ottcn.com^'
  - '||business.video.tc.skysrt.com^'
  - '||cl-dl.cc0808.com^'
  - '||clog.skysrt.com^'
  - '||conf-darwin.xycdn.com^'
  - '||connect.play.aiseet.atianqi.com^'
  - '||data-dl.skysrt.com^'
  - '||data-hoisin.coocaa.com^'
  - '||dl.skysrt.com^'
  - '||dp3.play.t002.ottcn.com^'
  - '||gs.getui.com^'
  - '||hoisin.coocaa.com^'
  - '||hoisin.coocaatv.com^'
  - '||irs01.com^'
  - '||kaola.com^'
  - '||livep.l.t002.ottcn.com^'
  - '||log.skysrt.com^'
  - '||mdp-at.geely.com^'
  - '||member.coocaa.com^'
  - '||miaozhen.com^'
  - '||mtrace.play.t002.ottcn.com^'
  - '||ocsp.int-x3.letsencrypt.org^'
  - '||p.tencentmind.com^'
  - '||play.t002.ottcn.com^'
  - '||push.tc.skysrt.com^'
  - '||push.tvos.skysrt.com^'
  - '||puui.qpic.cn^'
  - '||qr.coocaa.com^'
  - '||res.hoisin.coocaatv.com^'
  - '||rpc-tc.skysrt.com^'
  - '||rpt-gdt.play.t002.ottcn.com^'
  - '||s.jpush.cn^'
  - '||sdk1xyajs.data.p2cdn.com^'
  - '||sis.jpush.io^'
  - '||sky.tvos.skysrt.com^'
  - '||skyworthdigital.com^'
  - '||skyworthiot.com^'
  - '||stats.jpush.cn^'
  - '||status.tvos.skysrt.com^'
  - '||status2.tvos.skysrt.com^'
  - '||sv.video.qq.com^'
  - '||taps.net^'
  - '||tq.skysrt.com^'
  - '||tracker.appadhoc.com^'
  - '||tvapp.hpplay.cn^'
  - '||tvos.skysrt.com^'
  - '||tx.ctrmi.cn^'
  - '||umengacs.m.taobao.com^'
  - '||uop.umeng.com^'
  - '||update01.skyworth-cloud.com.wswebpic.com^'
  - '||update01.skyworth-cloud.com^'
  - '||vqq.admaster.com.cn^'
  - '||webapp.skysrt.com^'
  - '||bak.bajintech.com^$important^'
  - '||iwd.skysrt.com^$important^'
  - '||ipv4only.arpa^$important^'
  - '||api.bajintech.com^$important^'
  - '||wifimodule.doubimeizhi.com^$important^'
  - '||msy59wz.mqtt.iot.gz.baidubce.com^$important^'
  - '||i.ytimg.com^$important^'
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: Local
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  enabled: true
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 28
